# Sobre los autores {-}

## Elvis Caycho Villegas {-}

Matemático por la Universidad Nacional del Callao. Hizo una Maestría en Ciencia de la Educación Matemática por la Universidad Nacional Enrique Guzmán y Valle. Maestría en estadística matemática por la Universidad Nacional Mayor de San Marcos. Diplomado en investigación cuantitativa por la Universidad Nacional Enrique Guzmán y Valle.

## Antenor Escudero Gomez {-}

Politólogo de la Universidad Antonio Ruiz de Montoya, estudiante de maestría en Ciencia Política y Relaciones Internacionales por la Pontifica Universidad Católica del Perú. Actualmente trabaja en la Superintendencia Nacional de Educación Universitaria - SUNEDU como miembro del Equipo de Modificación de Licencia de la Dirección de Licenciamiento, desempeñandose anteriormente en el sector público. Tiene como temas de interés el comportamiento electoral, cultura política, historia del sindicalismo y estudios del trabajo.

## Nelly Reyes Mendoza {-}

Trabajadora Social de la Universidad Nacional Mayor de San Marcos, sin experiencia en el manejo de códigos en R Studio. Su experiencia laboral ha sido en instituciones privados y públicas referidas al sector educación en la implementación de programas y proyectos educativos en el MINEDU - Ministerio de Educación y la DRELM - Dirección Regional de Educación de Lima Metropolitana. Actualmente consultora independiente en temas de participación ciudadana, educación, juventudes y adolescencias. Colabora con la revista latinoamericana del CELATS - Centro Latinoamericano de Trabajo Social.Proviene de San Juan de Lurigancho, Lima - Perú. Tiene interés en temas de género, participación ciudadana y juventudes

## Leanna Sofía de los Ángeles Zúñiga Montaño {-}

Politóloga de la Universidad Antonio Ruiz de Montoya (UARM) y becada por la Alianza del Pacífico (2015) para llevar estudios en la Pontificia Universidad Javeriana de Bogotá. Tiene  conocimientos en políticas públicas, gestión pública, ciudadanía y comunicación para transformar conflictos e investigación académica. 
Se ha desempeñado en el sector privado como encargada de procesos de selección para voluntariado en la Fundación Internacional América Solidaria Internacional y en el sector público como analista en gestión y analista en políticas públicas en instituciones como Ministerio del Interior, Ministerio de Desarrollo e Inclusión Social- Programa Nacional de Alimentación Escolar Qali Warma, Ministerio de Educación y la Superintendencia Nacional de Educación Superior Universitaria-SUNEDU. 
Previo al taller no ha tenido experiencia en el uso de R para el análisis de datos, por lo que se encuentra interesada en aprender y emplearlo como herramienta para investigación y la gestión del conocimiento. 

## Samuel Calderon Serrano {-}

Politólogo de la Universidad Antonio Ruiz de Montoya. Fue el encargado de dictar el taller. Actualmente trabaja en la Superintendencia Nacional de Educación Universitaria - SUNEDU como miembro del Equipo Técnico Normativo de la Dirección de Licenciamiento. Aprendió a usar R el año 2019 y desde entonces ha tratado de “convertir” a otras personas. Miembro de la organización DecideBien, colabora ocasionalmente en iniciativas de código abierto. Proviene de Lima, Perú. Su experiencia laboral ha sido siempre en el sector público (Instituto Nacional de Estadística e Informática, Ministerio de Salud, Escuela Nacional de Administración Pública, Ministerio de Vivienda, Ministerio de Educación, SUNEDU). Tiene interés en los temas de educación superior, organizaciones electorales y datos abiertos.
